version: '3.8'

services:
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecommerce
      MONGO_INITDB_ROOT_PASSWORD: ecommercepassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ecommerce
      ME_CONFIG_MONGODB_ADMINPASSWORD: ecommercepassword
      ME_CONFIG_MONGODB_URL: mongodb://ecommerce:ecommercepassword@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
